### ISSUE TITLE
How To?

### ISSUE THREAD

**Issue by AzadWeb** [JesterSpearmann/TelegramDownloader#1]
Hi
Dear Jester
Can you tell me please how to connect that script to my bot?
I'm new about Telegram.
The bot is ready and I set the token in TelegramDownloader Script.
so now what is the next step...?
Thanks.

**Comment by JesterSpearmann** [comment]
You need a website to host your bot on for it to work then add it to your channel

**Comment by AzadWeb** [comment]
I have it. host is ready and all of that files uploaded on it.
I just don't know how to link it in my bot?
